server:
  port: 8888

spring:
  application:
    name: configservice
  security:
    user:
      name: config
      password: config
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/lgeorgieff/masteringSpringCloud.git
          searchPaths:
            - chapter_06/config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:eureka@localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh