server:
  port: 8888

spring:
  application:
    name: configservice
  security:
    user:
      name: config
      password: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lgeorgieff/masteringSpringCloud.git
          searchPaths:
            - chapter_06/config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:eureka@localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: refresh