server:
  port: ${PORT:8999}

eureka:
  client:
    registerWithEureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: echo_1
          uri: lb://echo-service-1
          predicates:
            - Method=GET
            - Path=/echo/1/{message}
          filters:
            - RewritePath=/echo/1/(?<message>), /echo/$\{message}
        - id: echo_2
          uri: lb://echo-service-2
          predicates:
            - Method=GET
            - Path=/echo/2/**
          filters:
            - RewritePath=/echo/2/(?<message>), /echo/$\{message}