server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: service-discovery-server
  security:
    user:
      name: admin
      password: secret